Minimal example of bug with coordinate format
Same data as previous (working) category format graph, but it causes a
TypeError: ranges[tickCount - 1] is undefined